nfsServer:
  image:
    repository: ghcr.io/sunu/nfs-ganesha
    tag: 402484a8540558e822b5eb092802fa65a09383cb

quotaEnforcer:
  image:
    repository: ghcr.io/sunu/get-quota-your-home
    tag: f9cf31cf51a1794b4c359dfa9aa7a6fe8a8f4c71
  # quota in GB
  hardQuota: "0.001"

persistentVolume:
  size: 10Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  annotations: {}

service:
  type: ClusterIP

# Cloud provider specific configurations
eks:
  enabled: false
  volumeId: "your-eks-volume-id"

gke:
  enabled: false
  volumeId: "your-gke-volume-id"