nfsServer:
  image:
    repository: ghcr.io/sunu/nfs-ganesha
    tag: 0.0.4

quotaEnforcer:
  image:
    repository: ghcr.io/sunu/get-quota-your-home
    tag: 0.0.4
  path: "/export"
  # quota in GB
  hardQuota: "10"

persistentVolume:
  size: 10Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  annotations: {}

service:
  type: ClusterIP

# Cloud provider specific configurations
eks:
  enabled: false
  volumeId: "your-eks-volume-id"

gke:
  enabled: false
  volumeId: "your-gke-volume-id"
