apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-home-directories-claim
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: ""
  {{- if or .Values.eks.enabled .Values.gke.enabled }}
  volumeName: {{ .Release.Name }}-home-directories-volume
  {{- end }}
